# Your project's server will run on localhost:xxxx at this port
PORT: 8000

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"
  - "ios >= 7"

# UnCSS will use these settings
UNCSS_OPTIONS:
  html:
    - "src/**/*.html"
  ignore:
    - !!js/regexp .foundation-mq
    - !!js/regexp ^\.is-.*

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "dist"  
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "src/**/*"
    - "!src/{img,js,scss}/**/*"
  content:
    - "src/**/*.html"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "node_modules/foundation-sites/scss"
    - "node_modules/motion-ui/src"
  # Paths to JavaScript entry points for webpack to bundle modules
  jsdir:
    - "src/js/app.js"
  angulardir:
    - "src/angular/angular-sanitize.js"
    - "src/angular/angular-animate.js"
    - "src/angular/angular-loader.js"
    - "src/angular/angular-route.js"
    - "src/angular/angular-touch.js"
    - "src/angular/angular-resource.js"
    - "src/angular/angular-foundation.js"
    - "src/angular/ao-angular-app.js"
    - "src/angular/ao-framework/ao-controllers.js"
    - "src/angular/ao-framework/ao-routes.js"
  testingdir:
    - "src/testing"